WITH BONUS_GRADE AS
(
    SELECT EMP_NO,
    CASE 
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
)

SELECT 
    HE.EMP_NO,
    HE.EMP_NAME,
    BS.GRADE,
    CASE 
    WHEN GRADE = 'S' THEN SAL * 0.2
    WHEN GRADE = 'A' THEN SAL * 0.15
    WHEN GRADE = 'B' THEN SAL * 0.1
    ELSE 0 END AS BONUS
FROM HR_EMPLOYEES HE
JOIN BONUS_GRADE BS ON HE.EMP_NO = BS.EMP_NO
ORDER BY EMP_NO

